name: Build StockTracker

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

env:
  QT_VERSION: '6.6.0'
  CMAKE_VERSION: '3.16'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Ubuntu 22.04
            os: ubuntu-22.04
            qt_arch: gcc_64
            cmake_generator: "Unix Makefiles"
            artifact_name: StockTracker-Linux
            executable_extension: ""
            
          - name: Windows Latest
            os: windows-latest
            qt_arch: win64_msvc2019_64
            cmake_generator: "Visual Studio 17 2022"
            artifact_name: StockTracker-Windows
            executable_extension: ".exe"
            
          - name: macOS Latest
            os: macos-latest
            qt_arch: clang_64
            cmake_generator: "Unix Makefiles"
            artifact_name: StockTracker-macOS
            executable_extension: ""

    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.name }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ env.QT_VERSION }}
        arch: ${{ matrix.qt_arch }}
        cache: true
        modules: 'qtcharts qtnetworkauth'

    # Ubuntu specific dependencies
    - name: Install Ubuntu dependencies
      if: matrix.os == 'ubuntu-22.04'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          ninja-build \
          libgl1-mesa-dev \
          libxkbcommon-x11-0 \
          libxcb-icccm4 \
          libxcb-image0 \
          libxcb-keysyms1 \
          libxcb-render-util0 \
          libxcb-xinerama0 \
          libxcb-composite0 \
          libxcb-cursor0 \
          libxcb-damage0 \
          libxcb-dpms0 \
          libxcb-dri2-0 \
          libxcb-dri3-0 \
          libxcb-ewmh2 \
          libxcb-glx0 \
          libxcb-present0 \
          libxcb-randr0 \
          libxcb-record0 \
          libxcb-render0 \
          libxcb-res0 \
          libxcb-screensaver0 \
          libxcb-shape0 \
          libxcb-shm0 \
          libxcb-sync1 \
          libxcb-util1

    # Windows specific setup
    - name: Setup MSVC (Windows)
      if: matrix.os == 'windows-latest'
      uses: microsoft/setup-msbuild@v1.3

    # macOS specific dependencies
    - name: Install macOS dependencies
      if: matrix.os == 'macos-latest'
      run: |
        brew install cmake ninja

    - name: Create build directory
      run: mkdir build

    - name: Configure CMake
      working-directory: build
      run: |
        cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="${{ env.Qt6_DIR }}" -G "${{ matrix.cmake_generator }}"

    - name: Build application
      working-directory: build
      run: cmake --build . --config Release

    # Ubuntu: Create AppImage
    - name: Create AppImage (Ubuntu)
      if: matrix.os == 'ubuntu-22.04'
      run: |
        # Install linuxdeploy and Qt plugin
        wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
        wget https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
        chmod +x linuxdeploy*.AppImage
        
        # Create AppDir structure
        mkdir -p AppDir/usr/bin
        cp build/bin/stock-tracker AppDir/usr/bin/
        
        # Create desktop file
        mkdir -p AppDir/usr/share/applications
        cat > AppDir/usr/share/applications/stocktracker.desktop << EOF
        [Desktop Entry]
        Type=Application
        Name=StockTracker
        Comment=Stock Tracking Application
        Exec=stock-tracker
        Icon=stocktracker
        Categories=Finance;Office;
        EOF
        
        # Copy icon if exists
        if [ -f "images/logo.ico" ]; then
          mkdir -p AppDir/usr/share/icons/hicolor/256x256/apps
          cp images/logo.ico AppDir/usr/share/icons/hicolor/256x256/apps/stocktracker.ico
        fi
        
        # Remove problematic SQL drivers that cause issues
        if [ -d "${{ env.Qt6_DIR }}/plugins/sqldrivers" ]; then
          find "${{ env.Qt6_DIR }}/plugins/sqldrivers" -name "*mimer*" -delete || true
          find "${{ env.Qt6_DIR }}/plugins/sqldrivers" -name "*oracle*" -delete || true
        fi
        
        # Create AppImage with error handling
        export QML_SOURCES_PATHS=src
        export QMAKE=${{ env.Qt6_DIR }}/bin/qmake
        export LD_LIBRARY_PATH=${{ env.Qt6_DIR }}/lib:$LD_LIBRARY_PATH
        ./linuxdeploy-x86_64.AppImage --appdir AppDir --plugin qt --output appimage || {
          echo "AppImage creation failed, creating simple archive instead"
          mkdir -p StockTracker-Linux
          cp -r AppDir/usr/* StockTracker-Linux/
          tar -czf StockTracker-Linux.tar.gz StockTracker-Linux/
        }

    # Windows: Package with windeployqt
    - name: Package Windows application
      if: matrix.os == 'windows-latest'
      working-directory: build
      run: |
        # Run windeployqt from the proper bin folder
        & "${env:Qt6_DIR}\bin\windeployqt.exe" ".\bin\Release\stock-tracker.exe" --release --no-translations --no-system-d3d-compiler

        # Create distribution folder
        mkdir ..\dist
        xcopy /E /I .\bin\Release ..\dist\StockTracker\
      shell: pwsh
    - name: Verify Qt DLLs copied
      if: matrix.os == 'windows-latest'
      run: |
        Get-ChildItem -Recurse -Include Qt*.dll -Path build/Release
      shell: pwsh
    # macOS: Create app bundle and DMG
    - name: Package macOS application
      if: matrix.os == 'macos-latest'
      run: |
        # Check if app bundle exists, if not create it
        if [ ! -d "build/bin/stock-tracker.app" ]; then
          echo "App bundle not found, creating one..."
          mkdir -p build/bin/stock-tracker.app/Contents/{MacOS,Resources}
          
          # Copy executable
          cp build/bin/stock-tracker build/bin/stock-tracker.app/Contents/MacOS/
          chmod +x build/bin/stock-tracker.app/Contents/MacOS/stock-tracker
          
          # Create Info.plist
          cat > build/bin/stock-tracker.app/Contents/Info.plist << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleExecutable</key>
            <string>stock-tracker</string>
            <key>CFBundleIdentifier</key>
            <string>com.stocktracker.app</string>
            <key>CFBundleName</key>
            <string>StockTracker</string>
            <key>CFBundleVersion</key>
            <string>1.0</string>
            <key>CFBundleShortVersionString</key>
            <string>1.0</string>
            <key>CFBundleInfoDictionaryVersion</key>
            <string>6.0</string>
            <key>CFBundlePackageType</key>
            <string>APPL</string>
            <key>LSMinimumSystemVersion</key>
            <string>10.14</string>
            <key>NSHighResolutionCapable</key>
            <true/>
        </dict>
        </plist>
        EOF
          
          # Copy icon if exists
          if [ -f "images/logo.ico" ]; then
            cp images/logo.ico build/bin/stock-tracker.app/Contents/Resources/
          fi
        fi
        
        # Deploy Qt libraries to the app bundle
        echo "Deploying Qt libraries..."
        macdeployqt build/bin/stock-tracker.app -verbose=2
        
        # Verify app bundle structure
        echo "App bundle structure:"
        find build/bin/stock-tracker.app -type f | head -20
        
        # Create distribution folder
        mkdir dist
        
        # Create a ZIP (preserves app bundle structure better than tar)
        echo "Creating ZIP archive..."
        cd build/bin
        zip -r ../../dist/StockTracker-macOS.zip stock-tracker.app
        cd ../..
        
        # Create tar.gz with proper options for macOS
        echo "Creating tar.gz archive..."
        # Use gnutar if available (better compatibility), otherwise use system tar
        if command -v gnutar >/dev/null 2>&1; then
          gnutar --format=gnu -czf dist/StockTracker-macOS.tar.gz -C build/bin stock-tracker.app
        else
          # Use system tar with options that preserve resource forks and extended attributes
          tar -czf dist/StockTracker-macOS.tar.gz -C build/bin stock-tracker.app
        fi
        
        # Also create a simple folder structure for easy access
        echo "Creating simple distribution folder..."
        mkdir -p dist/StockTracker-macOS
        cp -R build/bin/stock-tracker.app dist/StockTracker-macOS/
        
        # Create installation script
        cat > dist/StockTracker-macOS/install.sh << 'EOF'
        #!/bin/bash
        echo "Installing StockTracker..."
        cp -R stock-tracker.app /Applications/
        echo "StockTracker has been installed to /Applications/"
        echo "You can now find it in Launchpad or run it from Applications folder"
        EOF
        chmod +x dist/StockTracker-macOS/install.sh
        
        # Create simple tar.gz of the folder
        tar -czf dist/StockTracker-macOS-Simple.tar.gz -C dist StockTracker-macOS
        
        echo "Created macOS packages:"
        ls -la dist/
        echo "ZIP contents:"
        unzip -l dist/StockTracker-macOS.zip | head -10

    # Upload artifacts
    - name: Upload Ubuntu AppImage
      if: matrix.os == 'ubuntu-22.04'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: |
          StockTracker-*.AppImage
          StockTracker-Linux.tar.gz

    - name: Upload Windows build
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: dist/

    - name: Upload macOS packages
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: |
          dist/StockTracker-macOS.zip
          dist/StockTracker-macOS.tar.gz
          dist/StockTracker-macOS-Simple.tar.gz

  # Create release on tag push
  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts/
    
    - name: Display structure of downloaded files
      run: ls -la artifacts/
    
    - name: Extract tag name
      id: tag
      run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
    
    - name: Prepare release assets
      run: |
        mkdir release-assets
        
        # Handle Linux artifacts (AppImage or tar.gz)
        if [ -f "artifacts/StockTracker-Linux/StockTracker-x86_64.AppImage" ]; then
          cp "artifacts/StockTracker-Linux/StockTracker-x86_64.AppImage" "release-assets/StockTracker-Linux-x86_64.AppImage"
        elif [ -f "artifacts/StockTracker-Linux/StockTracker-Linux.tar.gz" ]; then
          cp "artifacts/StockTracker-Linux/StockTracker-Linux.tar.gz" "release-assets/StockTracker-Linux.tar.gz"
        fi
        
        # Handle Windows artifacts
        if [ -d "artifacts/StockTracker-Windows" ]; then
          cd "artifacts/StockTracker-Windows"
          zip -r "../../release-assets/StockTracker-Windows.zip" *
          cd ../..
        fi
        
        # Handle macOS artifacts (multiple options)
        if [ -f "artifacts/StockTracker-macOS/StockTracker-macOS.zip" ]; then
          cp "artifacts/StockTracker-macOS/StockTracker-macOS.zip" "release-assets/StockTracker-macOS.zip"
        fi
        if [ -f "artifacts/StockTracker-macOS/StockTracker-macOS.tar.gz" ]; then
          cp "artifacts/StockTracker-macOS/StockTracker-macOS.tar.gz" "release-assets/StockTracker-macOS.tar.gz"
        fi
        if [ -f "artifacts/StockTracker-macOS/StockTracker-macOS-Simple.tar.gz" ]; then
          cp "artifacts/StockTracker-macOS/StockTracker-macOS-Simple.tar.gz" "release-assets/StockTracker-macOS-Simple.tar.gz"
        fi
        
        # List what we have
        echo "Release assets prepared:"
        ls -la release-assets/
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.tag.outputs.tag }}
        name: StockTracker ${{ steps.tag.outputs.tag }}
        draft: false
        prerelease: false
        body: |
          ## Changes in this release
          - Automated build for Linux, Windows, and macOS
          - Built with Qt ${{ env.QT_VERSION }}
          
          ## Downloads
          - **Linux**: Download the `.AppImage` file (or `.tar.gz` if AppImage failed)
          - **Windows**: Download and extract the ZIP file
          - **macOS**: Download and extract the ZIP file (or `.tar.gz` alternative)
          
          ## Installation
          ### Linux
          **AppImage:**
          1. Download the AppImage
          2. Make it executable: `chmod +x StockTracker-*.AppImage`
          3. Run: `./StockTracker-*.AppImage`
          
          **Tar.gz:**
          1. Download and extract: `tar -xzf StockTracker-Linux.tar.gz`
          2. Run: `./StockTracker-Linux/bin/stock-tracker`
          
          ### Windows
          1. Download and extract the ZIP file
          2. Run `stock-tracker.exe`
          
          ### macOS
          ### macOS
          **ZIP (Recommended):**
          1. Download the ZIP file
          2. Extract it: `unzip StockTracker-macOS.zip`
          3. Drag `stock-tracker.app` to Applications folder
          4. If blocked by security, right-click the app → "Open" → "Open" to bypass
          
          **Simple tar.gz (Easy Installation):**
          1. Download `StockTracker-macOS-Simple.tar.gz`
          2. Extract: `tar -xzf StockTracker-macOS-Simple.tar.gz`
          3. Run the install script: `cd StockTracker-macOS && ./install.sh`
          4. Or manually drag `stock-tracker.app` to Applications
          
          **Regular tar.gz:**
          1. Download and extract: `tar -xzf StockTracker-macOS.tar.gz`
          2. Double-click the extracted `stock-tracker.app` to run
        files: release-assets/*
        fail_on_unmatched_files: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}